### ISSUE TITLE
Images are too big

### ISSUE THREAD

**Issue by SantiagoTorres** [in-toto/Dockerfiles#1]
The images are around 120MB.

This is quite likely because of the build toolchain (e.g., python headers, compilers and other tools).

We should strip them out of the `base` image during the build or use a [multi-stage build](https://docs.docker.com/engine/userguide/eng-image/multistage-build/#use-multi-stage-builds)

**Comment by kevholmes** [comment]
@SantiagoTorres Is this still a good issue to work on? I noticed the base/Dockerfile is using Python 2 and upstream in-toto has dropped support for that. I could work on updating the base Dockerfile to support Python 3 along with eliminating any bloat from unnecessary packages or libraries included with the final container image that's generated - using multi-stage builds or other common methods.

**Comment by SantiagoTorres** [comment]
Oh, this would be greatly appreciated!
